# Generated by Django 3.0.6 on 2020-06-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20200608_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='title',
        ),
    ]
